apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-lavq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-lavq
    app.kubernetes.io/part-of: build-suite-component-update-nitk
  name: multi-component-child-lavq
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: multi-component-child-lavq
status:
  loadBalancer: {}
