apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-parent-lavq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-parent-lavq
    app.kubernetes.io/part-of: build-suite-component-update-nitk
  name: multi-component-parent-lavq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-parent-lavq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-parent-lavq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-zjpq-tenant/build-suite-component-update-nitk/multi-component-parent-lavq@sha256:1c59590ee096b1f28945eb69ef6644cfdc72435a77d3311d0fd7097fecb7a96b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
